### PR TITLE
Constants example

### PR DESCRIPTION
**Pull request by bcorfman**
Hi, I created a PR with an example to demonstrate the problems I'm having with this current implementation of :constants.
The code submitted previously in PR 6 worked for these example files. I know you were trying to share the parser.objects with parser.constants, but :constants are defined ahead of :objects in the airport example, so the sharing method proposal needs additional consideration. Although I attempted a fix by using defaultdict for parser.objects instead, it's still not working. I don't know what you want to do here, so I'm just submitting the failing test for you to look at first.

As part of this PR (since I don't have access to TravisCI), I created a github-actions.yml file as well to run your same tests for me without needing to push to your repo first.

### CODE REVIEW

**Comment by Maumagnaguagno** [comment]
I am trying to parse both constants and objects the same way, as some users eventually move descriptions from/to constants and objects.
Travis should work fine, it seems the conflict is stopping it from running in the first place.
I am not considering adding GitHub Actions in this repo, as it would consume time from the university organization, which I am no longer part of.
I am against using defaultdict as some users are pretty young and won't realize how to verify key existence without triggering the default behavior and adding key/value to the structure.

I will test your example and fix it soon.
This repository is deviating quite a lot from my original vision of a propositional parser/planner with basic Python, which means bugs appearing, sorry about that.

**Comment by Maumagnaguagno** [comment]
It seems to be working in the last version:
```
plan:
move_seg_rw_0_400_seg_rww_0_50_south_south_medium airplane_cfbeg
move_seg_rww_0_50_seg_tww4_0_50_south_north_medium airplane_cfbeg
move_seg_tww4_0_50_seg_tww3_0_50_north_north_medium airplane_cfbeg
move_seg_tww3_0_50_seg_tww2_0_50_north_north_medium airplane_cfbeg
move_seg_tww2_0_50_seg_tww1_0_200_north_north_medium airplane_cfbeg
move_seg_tww1_0_200_seg_ppdoor_0_40_north_south_medium airplane_cfbeg
move_seg_ppdoor_0_40_seg_pp_0_60_south_south_medium airplane_cfbeg
park_seg_pp_0_60_south airplane_cfbeg
```
Can you clone the last version in a different folder and test again?

**Comment by bcorfman** [comment]
Do you mean you see the code working in your master branch? It doesn't work for me at all on that airport example using the current master.
`domain is not recognized in problem`
`:types is not recognized in problem`
`:constants is not recognized in problem`
`:predicates is not recognized in problem`
`:action is not recognized in problem`
`...`
`Time: 0.007728099822998047s`
`No plan was found`

**Comment by bcorfman** [comment]
My idea was to make the PDDL parsing slightly more robust to allow me to evaluate more complete cases with the planner. If my intent is beyond what you want to do with the code, then of course I can just develop my ideas on a fork.

**Comment by Maumagnaguagno** [comment]
I just committed the airport example, it is running just fine on Travis CI.
Not sure what is happening in your fork.

**Comment by bcorfman** [comment]
@Maumagnaguagno Somehow I got the airport domain file right but not the actual problem file. I checked that in, and modified the planner.py test to raise an Exception if no plan is found. (The test was executing, but mistakenly returning an exit code of 0 even when it didn't run properly.) Could you please take a look when you have a minute and see if you get the same failing test?

**Comment by Maumagnaguagno** [comment]
I fixed empty plans showing as failure and the exit code.
You somehow defined the domain in the problem file.

**Comment by bcorfman** [comment]
Wow, I really goofed that up. Too many cloned directories, and not paying enough attention to what I was doing. Thanks for the kind correction.

**Comment by Maumagnaguagno** [comment]
I am closing this PR as the Airport example works fine.

**Comment by meneguzzi** [comment]
> I am trying to parse both constants and objects the same way, as some users eventually move descriptions from/to constants and objects.
> Travis should work fine, it seems the conflict is stopping it from running in the first place.
> I am not considering adding GitHub Actions in this repo, as it would consume time from the university organization, which I am no longer part of.
> I am against using defaultdict as some users are pretty young and won't realize how to verify key existence without triggering the default behavior and adding key/value to the structure.
> 
> I will test your example and fix it soon.
> This repository is deviating quite a lot from my original vision of a propositional parser/planner with basic Python, which means bugs appearing, sorry about that.

Hi everyone, I don't mind using the organization's time, if Github or Travis decide to charge me for it, I will just migrate elsewhere. They should still be giving me free plans because this is an open source university project.

**Comment by Maumagnaguagno** [comment]
They both consume "time credits", Travis will start doing it in 2021 with a very low amount for free users.
Not sure what happens once you run out of credits, probably an email sent to the repo owner, not sure how many repos/time the organization is currently consuming.
I learned about GitHub Actions a few weeks ago, I will add it here if Travis is not enough.

**Comment by bcorfman** [comment]
My reading of the GitHub policy is that Actions are free for public repos and are only restricted to 2,000 min/month for private repos.
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Pull request closed without merging**
