### PR TITLE
Parses predicates

### PR DESCRIPTION
**Pull request by Behery**
Parses predicates from the domain file into `parser.predicates`

### CODE REVIEW

**Comment by Maumagnaguagno** [comment]
Usually ``:predicates`` are useful for debugging or programming languages that must allocate memory beforehand.
Without predicate name, variable names, arity and type checks you are not actually going for debugging, and Python does not need to allocate memory beforehand.

- What is your use case for this pull request?
- Do we need to save the variable names and types of each variable without support for types in this implementation?
- Why not just a tuple for predicates instead of a class?
There is also a ``print`` that appears to be a leftover.

**Comment by Behery** [comment]
Hi @Maumagnaguagno 

>What is your use case for this pull request?

I was writing a translator from PDDL to something else and I wanted to parse the predicates in order to properly handle the actions. It made my life easier and was marked as TODO in the parser so I thought I make a PR.

> Do we need to save the variable names and types of each variable without support for types in this implementation?

I think it's better -at least in my case- than not having them at all. Maybe the support comes in a later PR.

> Why not just a tuple for predicates instead of a class?

I can see that having them as tuple would make arty checks more straight forward. The `arguments` attribute of `Predicate` is a dictionary containing variable names and types which I think is easier for type checking (not sure though, since this isn't really my cup of tea). 
In any case, If you're planning on making type/arity checks I guess this would serve as a starting point.

>There is also a print that appears to be a leftover

oops... just removed it now sorry

**Comment by Maumagnaguagno** [comment]
The TODOs were intended for students to use as a starting point for their own projects, I never expected someone outside class would consider filling them.

> In any case, If you're planning on making type/arity checks I guess this would serve as a starting point.

I already have my debugger, that is how I know about these things, I am just trying to figure out your goal to help :D

The parser implemented here is a smaller version of the one I originally implemented in Ruby for [HyperTensioN](https://github.com/Maumagnaguagno/HyperTensioN/blob/master/parsers/PDDL_Parser.rb) to fill the gap between PDDL and HTN planning, with some translations and logs handled by an Intermediate Representation and a modular system, which may be of interest to you.

Our [new repository](https://github.com/pucrs-automated-planning/heuristic-planning) may be a better starting point.
There is basic support for types (still no either, subtypes or shared type, as in ``?x ?y - type``, support) and action grounding.

I would modify several parts of your implementation to make it more readable:
- Prefer ``self.predicates`` to be a dictionary with each key being a predicate name and the value being the arguments. This would replace your first inner loop with ``if predicate_name in self.predicates:``.
- Your second loop should iterate and test against hyphen and only them type the previous untyped variables and move the index of the untyped to the one after type. You can see how I did that in the PDDL Parser from HyperTensioN.

That means no predicate class, but a predicates structure ``{'pre1': {'?v1': 'type1', '?v2': 'type2'}, ...}`` where you can iterate and query easily for variable types (which I imagine is the important part for you), as in ``self.predicates['pre1']['?v2']``.

I guess I could port the parser from the other repository to this one while you make such changes, this part of the code is really independent from the rest.
Just give me one or two days to do this without breaking anything.
We will need to add tests too.

**Comment by Behery** [comment]
> The TODOs were intended for students to use as a starting point for their own projects, I never expected someone outside class would consider filling them.

I'm sorry i found the repo through google I didn't know that it belongs to a class :D 

> I guess I could port the parser from the other repository to this one while you make such changes, this part of the code is really independent from the rest.
Just give me one or two days to do this without breaking anything.

If that's too much hassle then don't bother I'm just working on a small project. If you were planning on doing this anyway then I'd gladly do the required changes on my side. 

Thanks for all the tips though, I'll take a look at HyperTensioN and the new repo :)

**Comment by Maumagnaguagno** [comment]
I planned to do this eventually, maybe not on this repository, as it was intended as a simple propositional planner.
Any of the changes we are talking about would also change the documentation and the scope of the parser and planner.
I will make a release of the current version, with a few less TODOs, and add the new parts to it.
It may take some time, as I do not want to add a lot of code in a single commit and have problems reverting/fixing some parts later.

**Comment by Maumagnaguagno** [comment]
Okay, I updated the parser and after your pull request gets merged I will continue updating the planner parts.
Just remember to use 4 spaces as indentation to keep it consistent with the rest of the code.

**Comment by meneguzzi** [comment]
Hi everyone,

First of all, thank you @Behery  for your interest in our work and for your contributions.

Second, @Maumagnaguagno , we should talk about how to best merge this in the repository. At the moment we are not actively using this parser for a lecture, but we may want to do so in the future, but then we could create an entirely new repository. I think we cab merge the pull request and have a general purpose PDDL parser in Python here.

I would also suggest comparing features with [PyperPlan](https://bitbucket.org/malte/pyperplan/src/default/) from Malte. I haven't tried to look at their parser in detail.

Best,

Felipe

**Comment by Maumagnaguagno** [comment]
@meneguzzi we are using an improved version of this parser in the [Heuristic planning](https://github.com/pucrs-automated-planning/heuristic-planning) repository, behind the Python Notebooks. I just moved some new parts from there to support typing and grounding.

@Behery I will accept your pull request and do the changes I believe will improve both speed and code readability myself, thanks for the pull request.

Feature comparison with other planners may require a few more tweaks, more specifically in the action parameters shared types still not supported: ``?x ?y - type``.

**Comment by Behery** [comment]
Hi everyone,

sorry I didn't have the time to implement the changes, I'm in a summerschool at the moment and was planning to implement the changes when I get home. But I see @Maumagnaguagno already did them and merged, so thanks, and also thanks for the discussion. Thank you both for the responses :) :) 

Cheers!

**Pull request merged**
